// Build static/js/editor.js from static/js/src/editor.js.
//
// The Content Security Policy is `default-src 'self'`, so every script must
// be a file that this host serves. CodeMirror is therefore bundled into one
// self-contained file rather than loaded from a CDN.
//
// Node is a build-time dependency only. The runtime is the Rust binary plus
// the files in static/.

import { build } from "esbuild";

const ENTRY = "static/js/src/editor.js";
const TARGET = "static/js/editor.js";

const BANNER = `/*
 * CookLangHub Recipe editor, with CodeMirror 6 bundled in.
 *
 * GENERATED by scripts/build-editor.mjs from ${ENTRY}. Do not edit this
 * file. Edit the source and run \`npm run build-editor\`.
 *
 * The editor and the Cooklang mode are adapted from CookCLI.
 * Copyright (c) 2021-2023 Alexey Dubovskoy, MIT. See LICENSE-MIT-cookcli
 * and NOTICE.
 *
 * CodeMirror 6 is copyright Marijn Haverbeke and others, MIT.
 */
`;

await build({
  entryPoints: [ENTRY],
  outfile: TARGET,
  bundle: true,
  // An IIFE keeps the page free of module attributes and needs no import
  // map, so one <script src> tag is enough.
  format: "iife",
  minify: true,
  // Every browser this project supports is evergreen.
  target: ["es2020"],
  banner: { js: BANNER },
  legalComments: "none",
  logLevel: "info",
});

console.log(`wrote ${TARGET}`);
